In [2]:
import numpy as np

# Numpy Basics

In [3]:
#1. Write a Numpy program to get the Numpy version and show the Numpy build configuration.
print(np.__version__)
print(np.show_config())

1.26.2
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /c/opt/64/include
    lib directory: /c/opt/64/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= SKYLAKEX MAX_THREADS=2
    pc file directory: C:/opt/64/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep1519489905472
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.2
Compilers:
  c:
    commands: cl
    linker: link
    name: msvc
    version: 19.29.30152
  c++:
    commands: cl
    linker: link
    name: msvc
    version: 19.29.30152
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.5
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows


In [4]:
#2. Write a NumPy program to get help with the add function.
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [5]:
#3. Write a NumPy program to test whether none of the elements of a given array are zero. 
x = np.array([1,2,3,4])
print(x)
print(np.all(x))

x = np.array([0,2,3,4])
print(x)
print(np.all(x))

[1 2 3 4]
True
[0 2 3 4]
False


In [6]:
#4. Write a NumPy program to test if any of the elements of a given array are non-zero. 
x = np.array([0,0,0,0])
print(x)
print(np.any(x))

x = np.array([0,2,3,4])
print(x)
print(np.any(x))

[0 0 0 0]
False
[0 2 3 4]
True


In [7]:
#5. Write a NumPy program to test a given array element-wise for finiteness (not infinity or not a number).
x = np.array([1,2,np.nan,np.inf])
print(x)
print(np.isinf(x))

[ 1.  2. nan inf]
[False False False  True]


In [8]:
#6. Write a NumPy program to test elements-wise for positive or negative infinity. 
x = np.array([1,2,-np.inf,np.inf])
print(x)
print(np.isinf(x))

[  1.   2. -inf  inf]
[False False  True  True]


In [9]:
#7. Write a NumPy program to test element-wise for NaN of a given array.
x = np.array([1,2,np.nan,4])
print(x)
print(np.isnan(x))

[ 1.  2. nan  4.]
[False False  True False]


In [10]:
#8. Write a NumPy program to test element-wise for complex numbers, real numbers in a given array. Also test if a given number is of a scalar type or not. 
x = np.array([1 + 1j, 1, 0.5])
print(x)
print(np.iscomplex(x))
print(np.isreal(x))
print(np.isscalar(1.2))
print(np.isscalar([1.2]))

[1. +1.j 1. +0.j 0.5+0.j]
[ True False False]
[False  True  True]
True
False


In [11]:
#9. Write a NumPy program to test whether two arrays are element-wise equal within a tolerance.
a = np.array([1e10, 1e-7])
b = np.array([1.00001e10, 1e-8])
c = np.array([1.00001e10, 1.00001e-7])
print(np.allclose(a,b))
print(np.allclose(a,c))

False
True


In [12]:
#10. Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays.
x = np.array([1,2,3])
y = np.array([2,2,2])
print(np.greater(x,y))
print(np.greater_equal(x,y))
print(np.less(x,y))
print(np.less_equal(x,y))

[False False  True]
[False  True  True]
[ True False False]
[ True  True False]


In [13]:
#11. Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given arrays.
x = np.array([1,2,3])
y = np.array([2,2,2])
print(np.equal(x,y))
print(np.allclose(x,y))

[False  True False]
False


In [14]:
#12. Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array.
x = np.array([1,7,13,105])
print(x)
print(x.size * x.itemsize)

[  1   7  13 105]
16


In [15]:
#13. Write a NumPy program to create an array of 10 zeros, 10 ones, and 10 fives. 
x = np.zeros(10)
y = np.ones(10)
z = np.ones(10) * 5
print(x)
print(y)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [16]:
#14. Write a NumPy program to create an array of integers from 30 to 70.
x = np.arange(30,71)
print(x)

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [17]:
#15.Write a NumPy program to create an array of all even integers from 30 to 70.
x = np.arange(30, 71, 2)
print(x)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [18]:
#16. Write a NumPy program to create a 3x3 identity matrix.
x = np.identity(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [19]:
#17. Write a NumPy program to generate a random number between 0 and 1.
x = np.random.rand()
print(x)

0.6115029629260218


In [20]:
#18. Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.
x = np.random.normal(size=15)
print(x)

[ 0.28946155  0.17977042 -0.9838325  -0.22753454 -0.30067558 -0.87331901
 -1.27260203  0.95792483 -0.3988304   0.29649807 -2.44595869 -1.02847974
  0.06192383 -0.21830393 -0.38143746]


In [21]:
#19. Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last.
x = np.arange(15,55)
print(x[1:-1])

[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53]


In [22]:
#20. Write a NumPy program to create a 3X4 array and iterate over it.
x = np.ones((3,4))
for i in np.nditer(x):
    print(i)

1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0


In [23]:
#21. Write a NumPy program to create a vector of length 10 with values evenly distributed between 5 and 50.
x = np.linspace(5,50,10)
print(x)

[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


In [24]:
#22. Write a NumPy program to create a vector with values from 0 to 20 and change the sign of the numbers in the range from 9 to 15.
x = np.arange(0, 21)
x[(x >= 9) & (x <= 15)] *= -1
print(x)

[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


In [25]:
#23. Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10.
x = np.random.randint(0, 11, 5)
print(x)

[7 9 1 3 4]


In [26]:
#24. Write a NumPy program to multiply the values of two given vectors.
x = np.array([1, 8, 3])
y = np.array([2, 2, 2])
print(np.multiply(x, y))
print(x*y)

[ 2 16  6]
[ 2 16  6]


In [27]:
#25. Write a NumPy program to create a 3x4 matrix filled with values from 10 to 21.
x = np.arange(10, 22).reshape((3, 4))
print(x)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [28]:
#26. Write a NumPy program to find the number of rows and columns in a given matrix.
x = np.array([[1, 2, 3, 4], 
              [5, 6, 7, 8], 
              [9, 10, 11, 12]])
print(x.shape)

(3, 4)


In [29]:
#27. Write a NumPy program to create a 3x3 identity matrix, i.e. the diagonal elements are 1, the rest are 0.
x = np.identity(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [30]:
#28. Write a NumPy program to create a 10x10 matrix, in which the elements on the borders will be equal to 1, and inside 0.
x = np.ones((10, 10))
x[1:-1, 1:-1] = 0
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [31]:
#29. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.
x = np.diag(np.arange(1, 6))
print(x)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [32]:
#30. Write a NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal.
x = np.zeros((4, 4))
x[::2, 1::2] = 1
x[1::2, ::2] = 1
print(x)

[[0. 1. 0. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]
 [1. 0. 1. 0.]]


In [33]:
#31. Write a NumPy program to create a 3x3x3 array filled with arbitrary values.
x = np.random.random((3, 3, 3))
print(x)

[[[0.43231574 0.97565476 0.98129338]
  [0.85919468 0.88944384 0.25496096]
  [0.9417753  0.96616881 0.49356601]]

 [[0.67657078 0.41871269 0.70512029]
  [0.13779553 0.84868318 0.5306472 ]
  [0.74161174 0.33021135 0.82733079]]

 [[0.22622777 0.88428274 0.47867207]
  [0.36791918 0.26655023 0.23333677]
  [0.66940315 0.33672857 0.19577732]]]


# NumPy Array

In [34]:
#2. Write a NumPy program to convert a list of numeric values into a one-dimensional NumPy array.
a = [1, 2, 3, 4]
x = np.array(a)
print(x)

[1 2 3 4]


In [35]:
#3.Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.
x = np.arange(2, 11).reshape(3, 3)
print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [36]:
#4. Write a NumPy program to create a null vector of size 10 and update the sixth value to 11.
x = np.zeros(10)
x[5] = 11
print(x)

[ 0.  0.  0.  0.  0. 11.  0.  0.  0.  0.]


In [37]:
#5. Write a NumPy program to create an array with values ranging from 12 to 38.
x = np.arange(12, 39)
print(x)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37 38]


In [38]:
#6. Write a NumPy program to reverse an array (the first element becomes the last).
x = np.arange(12, 39)
x = np.flip(x)
print(x)

[38 37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15
 14 13 12]


In [39]:
#7. Write a NumPy program to convert an array to a floating type.
x = np.array([1, 2, 3, 4])
x = np.asfarray(x)
print(x)

[1. 2. 3. 4.]


In [40]:
#8. Write a NumPy program to create a 2D array with 1 on the border and 0 inside.
x = np.ones((5, 5))
x[1:-1, 1:-1] = 0
print(x)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [41]:
#9. Write a NumPy program to add a border (filled with 0's) around an existing array.
x = np.ones((3, 3))
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print(x)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [42]:
#10. Write a NumPy program to create an 8x8 matrix and fill it with a checkerboard pattern.
x = np.zeros((8,8))
x[1::2, ::2] = 1
x[0::2, 1::2] = 1
print(x)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


# NumPy Linear Algebra

In [43]:
# 1. Write a NumPy program to compute the multiplication of two given matrixes.
x = np.array([[1, 0], [1, 1]])
y = np.array([[3, 1], [2, 2]])
print(np.dot(x, y))

[[3 1]
 [5 3]]


In [44]:
#2. Write a NumPy program to compute the outer product of two given vectors.
x = np.array([[1, 0], [1, 1]])
y = np.array([[3, 1], [2, 2]])
print(np.outer(x, y))

[[3 1 2 2]
 [0 0 0 0]
 [3 1 2 2]
 [3 1 2 2]]


In [45]:
#3. Write a NumPy program to compute the cross product of two given vectors.
x = np.array([[1, 0], [1, 1]])
y = np.array([[3, 1], [2, 2]])
print(np.cross(x, y))

[1 0]


In [46]:
#4. Write a NumPy program to compute the determinant of a given square array.
x = np.array([[1, 0], [1, 1]])
print(np.linalg.det(x))

1.0


In [47]:
#5. Write a NumPy program to evaluate Einstein's summation convention of two given multidimensional arrays.
x = np.array([[1, 0], [1, 1]])
y = np.array([[3, 1], [2, 2]])
print(np.einsum("mk,kn", x, y))

[[3 1]
 [5 3]]


In [48]:
#6. Write a NumPy program to compute the inner product of vectors for 1-D arrays (without complex conjugation) and in higher dimension.
x = np.array([1, 0, 1, 1])
y = np.array([3, 1, 2, 2])
print(np.inner(x, y))

x = np.array([[1, 0], [1, 1]])
y = np.array([[3, 1], [2, 2]])
print(np.inner(x, y))

7
[[3 2]
 [4 4]]


In [49]:
#7. Write a NumPy program to compute the eigenvalues and right eigenvectors of a given square array.
x = np.array([[1, 0], [1, 1]])
eigen_value, eigen_vector = np.linalg.eig(x)
print(eigen_value, eigen_vector)

[1. 1.] [[ 0.00000000e+00  2.22044605e-16]
 [ 1.00000000e+00 -1.00000000e+00]]


In [50]:
#8. Write a NumPy program to compute the Kronecker product of two given mulitdimension arrays.
x = np.array([[1, 0], [1, 1]])
y = np.array([[3, 1], [2, 2]])
print(np.kron(x, y))

[[3 1 0 0]
 [2 2 0 0]
 [3 1 3 1]
 [2 2 2 2]]


In [51]:
#9. Write a NumPy program to compute the condition number of a given matrix.
x = np.array([[1, 0], [1, 1]])
print(np.linalg.cond(x))

2.6180339887498953


In [52]:
#10. Write a NumPy program to find a matrix or vector norm.
x = np.array([[1, 0], [1, 1]])
print(np.linalg.norm(x))

1.7320508075688772


# NumPy Random

In [53]:
#1. Write a NumPy program to generate five random numbers from the normal distribution.
x = np.random.normal(size=5)
print(x)

[ 0.04999553  1.22465902  0.26203726  1.35999674 -0.09730365]


In [54]:
#2. Write a NumPy program to generate six random integers between 10 and 30.
x = np.random.randint(10, 30, 6)
print(x)

[16 21 27 25 20 24]


In [55]:
#3. Write a NumPy program to create a 3x3x3 array with random values.
x = np.random.random((3, 3, 3))
print(x)

[[[0.78292907 0.50580316 0.75633168]
  [0.9170815  0.89993226 0.99338981]
  [0.66960093 0.24983725 0.60427207]]

 [[0.93608445 0.69948335 0.04179149]
  [0.1317909  0.96620283 0.9871203 ]
  [0.5595368  0.19154115 0.13979667]]

 [[0.19157161 0.06768368 0.71641248]
  [0.35521965 0.46917845 0.77823828]
  [0.72875997 0.52802199 0.14430988]]]


In [56]:
#4. Write a NumPy program to create a 5x5 array with random values and find the minimum and maximum values.
x = np.random.random((5, 5))
min, max = np.min(x), np.max(x)
print(x)
print(min, max)

[[0.31268002 0.28205623 0.72888023 0.26294569 0.50781936]
 [0.29347956 0.59014714 0.83151865 0.16895331 0.57572607]
 [0.00777566 0.48181489 0.02462627 0.07887757 0.27761238]
 [0.40875575 0.18227227 0.75981072 0.57030895 0.99570646]
 [0.49387725 0.79276184 0.49018254 0.16089096 0.48833299]]
0.0077756604895363735 0.9957064553839822


In [57]:
#5. Write a NumPy program to create a random 10x4 array and extract the first five rows of the array and store them into a variable.
x = np.random.random((10, 4))
y = x[5:, :]
print(x)
print(y)

[[0.72005623 0.00198481 0.86121886 0.60089274]
 [0.88665922 0.81409768 0.16785842 0.65017137]
 [0.85775358 0.1285929  0.68838722 0.89848789]
 [0.0237154  0.50579323 0.88796386 0.56892   ]
 [0.3976445  0.06397373 0.92144101 0.63570056]
 [0.26283671 0.29653951 0.27270184 0.35799654]
 [0.92516114 0.39993487 0.36380817 0.07309963]
 [0.02887963 0.67589604 0.04160854 0.20321106]
 [0.56909875 0.44862639 0.95534359 0.47468432]
 [0.96476391 0.92454341 0.05830592 0.52529222]]
[[0.26283671 0.29653951 0.27270184 0.35799654]
 [0.92516114 0.39993487 0.36380817 0.07309963]
 [0.02887963 0.67589604 0.04160854 0.20321106]
 [0.56909875 0.44862639 0.95534359 0.47468432]
 [0.96476391 0.92454341 0.05830592 0.52529222]]


In [58]:
#6. Write a NumPy program to shuffle numbers between 0 and 10 (inclusive).
x = np.arange(10)
np.random.shuffle(x)
print(x)

[6 1 8 0 3 9 4 5 7 2]


In [59]:
#7. Write a NumPy program to normalize a 3x3 random matrix.
x = np.random.random((3, 3))
x = (x - np.mean(x) / np.std(x))
print(x)

[[-1.5502188  -1.03211698 -0.77291893]
 [-1.3238979  -1.68807914 -1.28581792]
 [-0.78280354 -1.42589101 -0.95893312]]


In [60]:
#8. Write a NumPy program to create a random vector of size 10 and sort it.
x = np.random.random(10)
x = np.sort(x)
print(x)

[0.16211092 0.18266324 0.24082854 0.24886121 0.41188398 0.43494663
 0.50018721 0.53766671 0.70739807 0.86755742]


In [61]:
#9. Write a NumPy program to find the nearest value from a given value in an array.
x = np.random.uniform(1, 12, 5)
v = 5
n = x.flat[np.abs(x - v).argmin()]
print(x)
print(n)

[ 2.46046808  9.05324788 10.86081315  2.60298134  1.54859965]
2.602981337169499


In [62]:
#10. Write a NumPy program to check two random arrays are equal or not.
x = np.random.randint(0, 2, 6)
y = np.random.randint(0, 2, 6)
equal = np.allclose(x, y)
print(x)
print(y)
print(equal)

[0 0 0 0 1 0]
[1 0 1 0 1 0]
False


# NumPy Sorting and Searching

In [63]:
#1. Write a NumPy program to sort a given array of shape 2 along the first axis, last axis and on flattened array.
x = np.array([[10, 40], [30, 20]])
print(np.sort(x, axis=0))
print(np.sort(x, axis=1))
print(np.sort(x, axis=None))

[[10 20]
 [30 40]]
[[10 40]
 [20 30]]
[10 20 30 40]


In [64]:
#2. Write a NumPy program to create a structured array from given student name, height, class and their data types. Now sort the array on height.
data_type = [('name', 'S15'), ('class', int), ('height', float)]
students_details = [(b'James', 5, 48.5 ), (b'Nail', 6, 52.5 ), (b'Paul', 5, 42.1 ),
(b'Pit', 5, 40.11)]
students = np.array(students_details, dtype=data_type)
print(np.sort(students, order='height'))

[(b'Pit', 5, 40.11) (b'Paul', 5, 42.1 ) (b'James', 5, 48.5 )
 (b'Nail', 6, 52.5 )]


In [65]:
#3. Write a NumPy program to create a structured array from given student name, height, class and their data types. Now sort by class, then height if class are equal.
data_type = [('name', 'S15'), ('class', int), ('height', float)]
students_details = [(b'James', 5, 48.5 ), (b'Nail', 6, 52.5 ), (b'Paul', 5, 42.1 ),
(b'Pit', 5, 40.11)]
students = np.array(students_details, dtype=data_type)
print(np.sort(students, order=['class', 'height']))

[(b'Pit', 5, 40.11) (b'Paul', 5, 42.1 ) (b'James', 5, 48.5 )
 (b'Nail', 6, 52.5 )]


In [68]:
#4. Write a NumPy program to sort the student id with increasing height of the students from given students id and height. Print the integer indices that describes the sort order by multiple columns and the sorted data.
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])
student_height = np.array([40., 42., 45., 41., 38., 40., 42.0])
indices = np.lexsort((student_id, student_height))
print(indices)
for index in indices:
    print(student_id[index], student_height[index])

[4 0 5 3 6 1 2]
1682 38.0
1023 40.0
5241 40.0
1671 41.0
4532 42.0
5202 42.0
6230 45.0


In [69]:
#5. Write a NumPy program to get the indices of the sorted elements of a given array.
x = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])
indices = np.argsort(x)
print(indices)

[0 3 4 6 1 5 2]


In [70]:
#6. Write a NumPy program to sort a given complex array using the real part first, then the imaginary part.
x = np.array([1 + 2j, 3 - 1j, 3 - 2j, 4 - 3j, 3 + 5j])
print(np.sort_complex(x))

[1.+2.j 3.-2.j 3.-1.j 3.+5.j 4.-3.j]


In [71]:
#7. Write a NumPy program to partition a given array in a specified position and move all the smaller elements values to the left of the partition, and the remaining values to the right, in arbitrary order (based on random choice).
x = np.array([70, 50, 20, 30, -11, 60, 50, 40])
print(np.partition(x, 4))

[-11  30  20  40  50  50  60  70]


In [73]:
#8. Write a NumPy program to sort the specified number of elements from beginning of a given array.
x = np.random.rand(10)
print(np.partition(x, 4)[:4])

[0.12639943 0.07141002 0.01903912 0.19202573]


In [82]:
#9. Write a NumPy program to sort an given array by the nth column.
x = np.random.randint(0, 10, (3, 3))
print(x[x[:, 1].argsort()])

[[3 4 2]
 [6 5 9]
 [6 7 3]]


# NumPy Mathematics

In [83]:
#1. Write a NumPy program to add, subtract, multiply, divide arguments element-wise.
x = 5
y = 1.5
print(np.add(x, y))
print(np.subtract(x, y))
print(np.multiply(x, y))
print(np.divide(x, y))

6.5
3.5
7.5
3.3333333333333335


In [88]:
#2. Write a NumPy program to compute logarithm of the sum of exponentiations of the inputs, sum of exponentiations of the inputs in base-2.
x = 5
y = 1.5
print(np.logaddexp(x, y))
print(np.logaddexp2(x, y))

5.029750418272621
5.122193416202275


In [87]:
#3. Write a NumPy program to get true division of the element-wise array inputs.
x = np.arange(10)
print(x)
print(np.true_divide(x, 2))

[0 1 2 3 4 5 6 7 8 9]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]


In [90]:
#4. Write a NumPy program to get the largest integer smaller or equal to the division of the inputs.
x = np.arange(10)
print(x)
print(np.floor_divide(x, 2))

[0 1 2 3 4 5 6 7 8 9]
[0 0 1 1 2 2 3 3 4 4]


In [92]:
#5. Write a NumPy program to get the powers of an array values element-wise.
x = np.arange(10)
print(x)
print(np.power(x, 3))

[0 1 2 3 4 5 6 7 8 9]
[  0   1   8  27  64 125 216 343 512 729]


In [93]:
#6. Write a NumPy program to get the element-wise remainder of an array of division.
x = np.arange(10)
print(x)
print(np.remainder(x, 2))

[0 1 2 3 4 5 6 7 8 9]
[0 1 0 1 0 1 0 1 0 1]


In [94]:
#7. Write a NumPy program to calculate the absolute value element-wise.
x = np.arange(-10, 0)
print(x)
print(np.absolute(x))

[-10  -9  -8  -7  -6  -5  -4  -3  -2  -1]
[10  9  8  7  6  5  4  3  2  1]


In [95]:
#8. Write a NumPy program to round array elements to the given number of decimals.
x = np.random.uniform(0, 10, 10)
print(x)
print(np.round(x, 2))

[7.88347223 7.25567504 3.09405436 3.77238624 5.16879727 2.38384013
 6.09464689 6.5528873  3.2948275  1.52489145]
[7.88 7.26 3.09 3.77 5.17 2.38 6.09 6.55 3.29 1.52]


In [96]:
#9. Write a NumPy program to round elements of the array to the nearest integer.
x = np.random.uniform(0, 10, 10)
print(x)
print(np.rint(x))

[8.70773126 2.89355677 8.9187718  0.26995806 3.68972543 0.3551595
 6.69381662 3.7176736  8.83766006 1.5294326 ]
[9. 3. 9. 0. 4. 0. 7. 4. 9. 2.]


In [97]:
#10. Write a NumPy program to get the floor, ceiling and truncated values of the elements of a numpy array.
x = np.random.uniform(0, 10, 10)
print(x)
print(np.floor(x))
print(np.ceil(x))
print(np.trunc(x))

[8.80409223 9.95242579 7.49946118 9.56174741 1.61091866 7.52350031
 1.11285471 9.0654099  2.95001228 3.25229682]
[8. 9. 7. 9. 1. 7. 1. 9. 2. 3.]
[ 9. 10.  8. 10.  2.  8.  2. 10.  3.  4.]
[8. 9. 7. 9. 1. 7. 1. 9. 2. 3.]


# NumPy Statistics

In [99]:
#1. Write a Python program to find the maximum and minimum value of a given flattened array.
x = np.arange(4).reshape(2, 2)
print(x)
print(np.min(x))
print(np.max(x))

[[0 1]
 [2 3]]
0
3


In [103]:
#2. Write a NumPy program to get the minimum and maximum value of a given array along the second axis.
x = np.arange(4).reshape(2, 2)
print(x)
print(np.min(x, axis=1))
print(np.max(x, axis=1))

[[0 1]
 [2 3]]
[0 2]
[1 3]


In [109]:
#3. Write a NumPy program to calculate the difference between the maximum and the minimum values of a given array along the second axis.
x = np.arange(1, 11).reshape(2, 5)
print(x)
print(np.ptp(x, 1))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[4 4]


In [114]:
#4. Write a NumPy program to compute the 80th percentile for all elements in a given array along the second axis.
x = np.arange(1, 11).reshape(2, 5)
print(x)
print(np.percentile(x, 80, 1))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[4.2 9.2]


In [112]:
#5. Write a NumPy program to compute the median of flattened given array.
x = np.arange(1, 11)
print(x)
print(np.median(x))

[ 1  2  3  4  5  6  7  8  9 10]
5.5


In [121]:
#6. Write a NumPy program to compute the weighted of a given array.
x = np.arange(5)
weights = np.arange(1, 6)
print(np.average(x, weights=weights))

2.6666666666666665


In [122]:
#7. Write a NumPy program to compute the mean, standard deviation, and variance of a given array along the second axis.
x = np.arange(1, 11).reshape(2, 5)
print(x)
print(np.mean(x, 1))
print(np.std(x, 1))
print(np.var(x, 1))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[3. 8.]
[1.41421356 1.41421356]
[2. 2.]


In [123]:
#8. Write a NumPy program to compute the covariance matrix of two given arrays.
x = np.array([0, 1, 2])
y = np.array([2, 1, 0])
print(np.cov(x, y))

[[ 1. -1.]
 [-1.  1.]]


In [125]:
#9. Write a NumPy program to compute cross-correlation of two given arrays.
x = np.array([0, 1, 3])
y = np.array([2, 4, 5])
print(np.correlate(x, y))

[19]


In [126]:
#10. Write a NumPy program to compute pearson product-moment correlation coefficients of two given arrays.
x = np.array([0, 1, 3])
y = np.array([2, 4, 5])
print(np.corrcoef(x, y))

[[1.         0.92857143]
 [0.92857143 1.        ]]


# NumPy DateTime 

In [134]:
import datetime

In [127]:
#1. Write a NumPy program to display all the dates for the month of March, 2017.
print(np.arange('2017-03', '2017-04', dtype='datetime64[D]'))

['2017-03-01' '2017-03-02' '2017-03-03' '2017-03-04' '2017-03-05'
 '2017-03-06' '2017-03-07' '2017-03-08' '2017-03-09' '2017-03-10'
 '2017-03-11' '2017-03-12' '2017-03-13' '2017-03-14' '2017-03-15'
 '2017-03-16' '2017-03-17' '2017-03-18' '2017-03-19' '2017-03-20'
 '2017-03-21' '2017-03-22' '2017-03-23' '2017-03-24' '2017-03-25'
 '2017-03-26' '2017-03-27' '2017-03-28' '2017-03-29' '2017-03-30'
 '2017-03-31']


In [128]:
#2. Write a NumPy program to get the dates of yesterday, today and tomorrow.
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today = np.datetime64('today', 'D')
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(yesterday, today, tomorrow)

2024-02-23 2024-02-24 2024-02-25


In [133]:
#3. Write a NumPy program to count the number of days of specific month.
print(np.datetime64('3000-03', 'D') - np.datetime64('3000-02', 'D'))

28 days


In [135]:
#4. Write a NumPy program to create 24 python datetime.datetime objects (single object for every hour), and then put it in a numpy array.
start = datetime.datetime(2000, 1, 1)
dt_array = np.array([start + datetime.timedelta(hours=i) for i in range(24)])
print(dt_array)

[datetime.datetime(2000, 1, 1, 0, 0) datetime.datetime(2000, 1, 1, 1, 0)
 datetime.datetime(2000, 1, 1, 2, 0) datetime.datetime(2000, 1, 1, 3, 0)
 datetime.datetime(2000, 1, 1, 4, 0) datetime.datetime(2000, 1, 1, 5, 0)
 datetime.datetime(2000, 1, 1, 6, 0) datetime.datetime(2000, 1, 1, 7, 0)
 datetime.datetime(2000, 1, 1, 8, 0) datetime.datetime(2000, 1, 1, 9, 0)
 datetime.datetime(2000, 1, 1, 10, 0) datetime.datetime(2000, 1, 1, 11, 0)
 datetime.datetime(2000, 1, 1, 12, 0) datetime.datetime(2000, 1, 1, 13, 0)
 datetime.datetime(2000, 1, 1, 14, 0) datetime.datetime(2000, 1, 1, 15, 0)
 datetime.datetime(2000, 1, 1, 16, 0) datetime.datetime(2000, 1, 1, 17, 0)
 datetime.datetime(2000, 1, 1, 18, 0) datetime.datetime(2000, 1, 1, 19, 0)
 datetime.datetime(2000, 1, 1, 20, 0) datetime.datetime(2000, 1, 1, 21, 0)
 datetime.datetime(2000, 1, 1, 22, 0) datetime.datetime(2000, 1, 1, 23, 0)]


In [136]:
#5. Write a NumPy program to find the first Monday in May 2017.
print(np.busday_offset('2017-05', 0, roll='forward', weekmask='Mon'))

2017-05-01


In [137]:
#6. Write a NumPy program to find the number of weekdays in March 2017.
print(np.busday_count('2017-03', '2017-04'))

23


In [138]:
#7. Write a NumPy program to convert numpy datetime64 to Timestamp.
dt64 = np.datetime64('2018-02-25 22:10:10')
ts = (dt64 - np.datetime64('1970-01-01T00:00:00Z')) / np.timedelta64(1, 's')
print(ts)

1519596610.0


C:\Users\bdm2k\AppData\Local\Temp\ipykernel_23036\2451610511.py:3: DeprecationWarning: parsing timezone aware datetimes is deprecated; this will raise an error in the future
  ts = (dt64 - np.datetime64('1970-01-01T00:00:00Z')) / np.timedelta64(1, 's')


# NumPy String

In [142]:
#1. Write a NumPy program to concatenate element-wise two arrays of string.
x = np.array(['Python', 'PHP'], dtype=str)
y = np.array([' Java', ' C++'], dtype=str)
print(np.char.add(x, y))

['Python Java' 'PHP C++']


In [143]:
#2. Write a NumPy program to repeat all the elements three times of a given array of string
x = np.array(['Python', 'PHP', 'Java', 'C++'], dtype=str)
print(np.char.multiply(x, 3))

['PythonPythonPython' 'PHPPHPPHP' 'JavaJavaJava' 'C++C++C++']


In [144]:
#3. Write a NumPy program to capitalize the first letter, lowercase, uppercase, swapcase, title-case of all the elements of a given array.
x = np.array(['python', 'PHP', 'java', 'C++'], dtype=str)
print(np.char.capitalize(x))
print(np.char.lower(x))
print(np.char.upper(x))
print(np.char.swapcase(x))
print(np.char.title(x))

['Python' 'Php' 'Java' 'C++']
['python' 'php' 'java' 'c++']
['PYTHON' 'PHP' 'JAVA' 'C++']
['PYTHON' 'php' 'JAVA' 'c++']
['Python' 'Php' 'Java' 'C++']


In [145]:
#4. Write a NumPy program to make the length of each element 15 of a given array and the string centered / left-justified / right-justified with paddings of _.
x = np.array(['python', 'PHP', 'java', 'C++'], dtype=str)
print(np.char.center(x, 15, fillchar='_'))
print(np.char.ljust(x, 15, fillchar='_'))
print(np.char.rjust(x, 15, fillchar='_'))

['_____python____' '______PHP______' '______java_____' '______C++______']
['python_________' 'PHP____________' 'java___________' 'C++____________']
['_________python' '____________PHP' '___________java' '____________C++']


In [146]:
#5. Write a NumPy program to insert a space between characters of all the elements of a given array.
x = np.array(['python', 'PHP', 'java', 'C++'], dtype=str)
print(np.char.join(' ', x))

['p y t h o n' 'P H P' 'j a v a' 'C + +']


In [147]:
#6. Write a NumPy program to encode all the elements of a given array in cp500 and decode it again.
x = np.array(['python', 'PHP', 'java', 'C++'], dtype=str)
print(np.char.encode(x, 'cp500'))
print(np.char.decode(np.char.encode(x, 'cp500'), 'cp500'))

[b'\x97\xa8\xa3\x88\x96\x95' b'\xd7\xc8\xd7' b'\x91\x81\xa5\x81' b'\xc3NN']
['python' 'PHP' 'java' 'C++']


In [150]:
#7. Write a NumPy program to remove the leading and trailing whitespaces of all the elements of a given array.
x = np.array([' python ', ' PHP ', ' java ', ' C++ '], dtype=str)
print(np.char.strip(x))

['python' 'PHP' 'java' 'C++']


In [151]:
#8. Write a NumPy program to remove the leading whitespaces of all the elements of a given array.
x = np.array([' python ', ' PHP ', ' java ', ' C++ '], dtype=str)
print(np.char.lstrip(x))

['python ' 'PHP ' 'java ' 'C++ ']


In [152]:
#9. Write a NumPy program to remove the trailing whitespaces of all the elements of a given array.
x = np.array([' python ', ' PHP ', ' java ', ' C++ '], dtype=str)
print(np.char.rstrip(x))

[' python' ' PHP' ' java' ' C++']


In [153]:
#10. Write a NumPy program to split the element of a given array with spaces.
x = np.array(['Python PHP Java C++'], dtype=str)
print(np.char.split(x))

[list(['Python', 'PHP', 'Java', 'C++'])]


# Advanced NumPy Exercises

In [157]:
#1. Write a NumPy program to find the dot product of two arrays of different dimensions.
x = np.array([[1, 2], [3, 4], [5, 6]])
y = np.array([4, 5])
print(np.dot(x, y))

[14 32 50]


In [161]:
#2. Write a NumPy program to create a 3x3 identity matrix and stack it vertically and horizontally.
x = np.identity(3)
print(x)
print(np.vstack((x, x, x)))
print(np.hstack((x, x, x)))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 1. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 1. 0. 0. 1. 0.]
 [0. 0. 1. 0. 0. 1. 0. 0. 1.]]


In [164]:
#3. Write a NumPy program to create a 4x4 array with random values and find the sum of each row.
x = np.random.rand(4, 4)
print(x)
print(x.sum(axis=1))

[[0.5321192  0.54821139 0.93953764 0.29415192]
 [0.61398708 0.4287171  0.57932102 0.9734945 ]
 [0.27299375 0.26177223 0.53564626 0.30704772]
 [0.96400916 0.62796439 0.8032034  0.47197322]]
[2.31402015 2.5955197  1.37745997 2.86715017]


In [166]:
#4. Write a NumPy program to create a 3x3 array with random values and subtract the mean of each row from each element.
x = np.random.rand(3, 3)
print(x)
print(x - x.mean(axis=1, keepdims=True))

[[0.22978662 0.50530855 0.60684867]
 [0.82505159 0.90114247 0.09665675]
 [0.59044053 0.9999594  0.65123583]]
[[-0.21752799  0.05799394  0.15953406]
 [ 0.21743465  0.29352553 -0.51096019]
 [-0.15677139  0.25274748 -0.09597609]]


In [167]:
#5. Write a NumPy program to create a 3x3 array with random values and subtract the mean of each column from each element.
x = np.random.rand(3, 3)
print(x)
print(x - x.mean(axis=0, keepdims=True))

[[0.37956113 0.59012376 0.48601038]
 [0.58491392 0.19917524 0.81714065]
 [0.55475788 0.2348042  0.45747782]]
[[-0.12684985  0.24875603 -0.1008659 ]
 [ 0.07850294 -0.1421925   0.23026436]
 [ 0.0483469  -0.10656354 -0.12939846]]


In [177]:
#6. Write a NumPy program to create a 5x5 array with random values and normalize it row-wise.
x = np.random.rand(5, 5)
print(x)
print(x - np.mean(x, axis=1) / np.std(x, axis=1))

[[0.43695397 0.16043243 0.48525188 0.10554784 0.33944198]
 [0.74416334 0.51324255 0.78279674 0.05966002 0.84850574]
 [0.57337558 0.57986057 0.13228799 0.3476992  0.49506267]
 [0.77394358 0.03820804 0.37270725 0.72719675 0.90857877]
 [0.96935729 0.92620286 0.68032109 0.27235203 0.85366218]]
[[-1.60653879 -1.88656739 -2.03559788 -1.67394538 -2.57602005]
 [-1.29932942 -1.53375727 -1.73805303 -1.7198332  -2.06695629]
 [-1.47011718 -1.46713925 -2.38856178 -1.43179402 -2.42039937]
 [-1.26954918 -2.00879178 -2.14814251 -1.05229647 -2.00688326]
 [-1.07413548 -1.12079696 -1.84052868 -1.50714119 -2.06179985]]


In [172]:
#7. Write a NumPy program to create a 5x5 array with random values and normalize it column-wise.
x = np.random.rand(5, 5)
print(x)
print(x - np.mean(x, axis=0) / np.std(x, axis=0))

[[0.6320455  0.56862856 0.4448491  0.29529761 0.09227731]
 [0.91655052 0.63417126 0.14540204 0.63947813 0.66046277]
 [0.77179346 0.51593772 0.3315866  0.16119035 0.63479788]
 [0.72231159 0.40440618 0.80509699 0.91570461 0.9166398 ]
 [0.75311385 0.00540622 0.63455378 0.00718531 0.98656661]]
[[-7.60379942 -1.3385182  -1.60863387 -0.92710042 -1.99853437]
 [-7.31929441 -1.2729755  -1.90808093 -0.5829199  -1.43034891]
 [-7.46405146 -1.39120904 -1.72189636 -1.06120768 -1.4560138 ]
 [-7.51353333 -1.50274057 -1.24838597 -0.30669342 -1.17417189]
 [-7.48273108 -1.90174053 -1.41892919 -1.21521272 -1.10424507]]


In [178]:
#8. Write a NumPy program to create a 3x3x3 array with random values and find the sum along the last axis.
x = np.random.rand(3, 3, 3)
print(x)
print(x.sum(axis=-1))

[[[0.13254635 0.46942967 0.9865747 ]
  [0.35151635 0.76021194 0.07852636]
  [0.55031517 0.56759247 0.01830477]]

 [[0.31903367 0.19971885 0.33708258]
  [0.62283782 0.02066311 0.81310629]
  [0.66107749 0.79565094 0.85153272]]

 [[0.77522971 0.66638135 0.13138806]
  [0.10410894 0.42066402 0.54367866]
  [0.37703285 0.41090276 0.61098017]]]
[[1.58855072 1.19025464 1.1362124 ]
 [0.8558351  1.45660722 2.30826115]
 [1.57299912 1.06845162 1.39891579]]


In [179]:
#9. Write a NumPy program to create a 5x5 array with random values and sort each row.
x = np.random.rand(5, 5)
print(x)
print(np.sort(x, axis=1))

[[0.53987866 0.48271576 0.41589943 0.01494049 0.15147009]
 [0.61336336 0.51426836 0.28440275 0.26378173 0.35106525]
 [0.0788042  0.33382824 0.26173166 0.89996379 0.88148152]
 [0.58938837 0.24836479 0.28963009 0.17354006 0.8870924 ]
 [0.72303945 0.85394706 0.10338035 0.59223851 0.18994857]]
[[0.01494049 0.15147009 0.41589943 0.48271576 0.53987866]
 [0.26378173 0.28440275 0.35106525 0.51426836 0.61336336]
 [0.0788042  0.26173166 0.33382824 0.88148152 0.89996379]
 [0.17354006 0.24836479 0.28963009 0.58938837 0.8870924 ]
 [0.10338035 0.18994857 0.59223851 0.72303945 0.85394706]]


In [181]:
#10. Write a NumPy program to create a 5x5 array with random values and sort each column.
x = np.random.rand(5, 5)
print(x)
print(np.sort(x, axis=0))

[[0.34829382 0.30323787 0.03231732 0.00863437 0.57805889]
 [0.82866682 0.69006739 0.46545024 0.05178934 0.72910236]
 [0.85692965 0.64848834 0.6993687  0.03213435 0.98468614]
 [0.87140634 0.75162425 0.30539928 0.85598173 0.83409005]
 [0.12604186 0.24503164 0.46489867 0.02188391 0.01895637]]
[[0.12604186 0.24503164 0.03231732 0.00863437 0.01895637]
 [0.34829382 0.30323787 0.30539928 0.02188391 0.57805889]
 [0.82866682 0.64848834 0.46489867 0.03213435 0.72910236]
 [0.85692965 0.69006739 0.46545024 0.05178934 0.83409005]
 [0.87140634 0.75162425 0.6993687  0.85598173 0.98468614]]


In [182]:
#11. Write a NumPy program to create a 5x5 array with random values and find the second-largest value in each row.
x = np.random.rand(5, 5)
print(x)
print(np.sort(x, axis=1)[:, -2])

[[0.49464414 0.63235138 0.15372151 0.517275   0.01701557]
 [0.6344592  0.14664209 0.78700297 0.52291734 0.09458724]
 [0.47765036 0.79210703 0.84343732 0.10066647 0.34910036]
 [0.25678455 0.52687556 0.67877213 0.72871387 0.29496257]
 [0.71337686 0.02635807 0.41787266 0.13081281 0.47513048]]
[0.517275   0.6344592  0.79210703 0.67877213 0.47513048]


In [183]:
#12. Write a NumPy program to create a 5x5 array with random values and find the second-largest value in each column.
x = np.random.rand(5, 5)
print(x)
print(np.sort(x, axis=0)[-2])

[[0.05305563 0.22814144 0.47909262 0.92414641 0.04753684]
 [0.22247183 0.74892613 0.35125782 0.37827198 0.37340916]
 [0.6716982  0.79385889 0.7882098  0.95054618 0.19236045]
 [0.63382497 0.82974618 0.83092288 0.1096405  0.07400546]
 [0.23226237 0.83350093 0.9479658  0.9387866  0.25453734]]
[0.63382497 0.82974618 0.83092288 0.9387866  0.25453734]


In [187]:
#13. Write a NumPy program to create a 5x5 array with random values and replace the maximum value with 0.
x = np.random.rand(5, 5)
print(x)
x[x == np.max(x)] = 0
print(x)


[[0.67227972 0.85642894 0.26283011 0.56124488 0.23005323]
 [0.78620018 0.89616089 0.89757266 0.12952158 0.07013815]
 [0.30753622 0.43372788 0.98159467 0.6394077  0.52654168]
 [0.14465163 0.76680405 0.53077026 0.15154698 0.00647437]
 [0.50211092 0.44789246 0.36099958 0.84771736 0.4205342 ]]
[[0.67227972 0.85642894 0.26283011 0.56124488 0.23005323]
 [0.78620018 0.89616089 0.89757266 0.12952158 0.07013815]
 [0.30753622 0.43372788 0.         0.6394077  0.52654168]
 [0.14465163 0.76680405 0.53077026 0.15154698 0.00647437]
 [0.50211092 0.44789246 0.36099958 0.84771736 0.4205342 ]]
7


In [188]:
#14. Write a NumPy program to create a 5x5 array with random values and replace the minimum value with 0.
x = np.random.rand(5, 5)
print(x)
x[x == np.min(x)] = 0
print(x)

[[0.56841606 0.59420355 0.1131246  0.80995004 0.0645489 ]
 [0.42988253 0.84005164 0.9174391  0.27560031 0.98079316]
 [0.02661907 0.80419258 0.97111019 0.87609515 0.60041596]
 [0.02719278 0.95672321 0.32504622 0.06746441 0.57232496]
 [0.38074536 0.33656937 0.04767692 0.87230425 0.56941433]]
[[0.56841606 0.59420355 0.1131246  0.80995004 0.0645489 ]
 [0.42988253 0.84005164 0.9174391  0.27560031 0.98079316]
 [0.         0.80419258 0.97111019 0.87609515 0.60041596]
 [0.02719278 0.95672321 0.32504622 0.06746441 0.57232496]
 [0.38074536 0.33656937 0.04767692 0.87230425 0.56941433]]


In [189]:
#15. Write a NumPy program to create a 5x5 array with random values and calculate the exponential of each element.
x = np.random.rand(5, 5)
print(x)
print(np.exp(x))

[[0.89915554 0.23032447 0.23429074 0.29476938 0.69846734]
 [0.20715376 0.47270146 0.43717333 0.48484669 0.07796991]
 [0.53429055 0.01789663 0.82620745 0.33615436 0.13256757]
 [0.22349947 0.82803772 0.20853935 0.64864712 0.2054966 ]
 [0.14544537 0.1873947  0.40780712 0.53340542 0.03791088]]
[[2.45752695 1.25900846 1.26401194 1.34281664 2.01066867]
 [1.23017171 1.60432236 1.54832443 1.62392602 1.08109013]
 [1.70623732 1.01805773 2.28463768 1.39955504 1.14175617]
 [1.25044497 2.28882302 1.23187741 1.91295108 1.2281348 ]
 [1.15655456 1.20610324 1.50351713 1.70472774 1.03863866]]
